*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZMHP_INT_C_V....................................*
FORM GET_DATA_ZMHP_INT_C_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZMHP_INT_CONVERS WHERE
(VIM_WHERETAB) .
    CLEAR ZMHP_INT_C_V .
ZMHP_INT_C_V-MANDT =
ZMHP_INT_CONVERS-MANDT .
ZMHP_INT_C_V-MOLGA =
ZMHP_INT_CONVERS-MOLGA .
ZMHP_INT_C_V-INFTY =
ZMHP_INT_CONVERS-INFTY .
ZMHP_INT_C_V-FIELD_SAP =
ZMHP_INT_CONVERS-FIELD_SAP .
ZMHP_INT_C_V-CONVERSION_METHOD =
ZMHP_INT_CONVERS-CONVERSION_METHOD .
ZMHP_INT_C_V-LAST_CHANGED_AT =
ZMHP_INT_CONVERS-LAST_CHANGED_AT .
ZMHP_INT_C_V-LAST_CHANGED_BY =
ZMHP_INT_CONVERS-LAST_CHANGED_BY .
<VIM_TOTAL_STRUC> = ZMHP_INT_C_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMHP_INT_C_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMHP_INT_C_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMHP_INT_C_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_CONVERS WHERE
  MOLGA = ZMHP_INT_C_V-MOLGA AND
  INFTY = ZMHP_INT_C_V-INFTY AND
  FIELD_SAP = ZMHP_INT_C_V-FIELD_SAP .
    IF SY-SUBRC = 0.
    DELETE ZMHP_INT_CONVERS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_CONVERS WHERE
  MOLGA = ZMHP_INT_C_V-MOLGA AND
  INFTY = ZMHP_INT_C_V-INFTY AND
  FIELD_SAP = ZMHP_INT_C_V-FIELD_SAP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZMHP_INT_CONVERS.
    ENDIF.
ZMHP_INT_CONVERS-MANDT =
ZMHP_INT_C_V-MANDT .
ZMHP_INT_CONVERS-MOLGA =
ZMHP_INT_C_V-MOLGA .
ZMHP_INT_CONVERS-INFTY =
ZMHP_INT_C_V-INFTY .
ZMHP_INT_CONVERS-FIELD_SAP =
ZMHP_INT_C_V-FIELD_SAP .
ZMHP_INT_CONVERS-CONVERSION_METHOD =
ZMHP_INT_C_V-CONVERSION_METHOD .
ZMHP_INT_CONVERS-LAST_CHANGED_AT =
ZMHP_INT_C_V-LAST_CHANGED_AT .
ZMHP_INT_CONVERS-LAST_CHANGED_BY =
ZMHP_INT_C_V-LAST_CHANGED_BY .
    IF SY-SUBRC = 0.
    UPDATE ZMHP_INT_CONVERS ##WARN_OK.
    ELSE.
    INSERT ZMHP_INT_CONVERS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMHP_INT_C_V-UPD_FLAG,
STATUS_ZMHP_INT_C_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMHP_INT_C_V.
  SELECT SINGLE * FROM ZMHP_INT_CONVERS WHERE
MOLGA = ZMHP_INT_C_V-MOLGA AND
INFTY = ZMHP_INT_C_V-INFTY AND
FIELD_SAP = ZMHP_INT_C_V-FIELD_SAP .
ZMHP_INT_C_V-MANDT =
ZMHP_INT_CONVERS-MANDT .
ZMHP_INT_C_V-MOLGA =
ZMHP_INT_CONVERS-MOLGA .
ZMHP_INT_C_V-INFTY =
ZMHP_INT_CONVERS-INFTY .
ZMHP_INT_C_V-FIELD_SAP =
ZMHP_INT_CONVERS-FIELD_SAP .
ZMHP_INT_C_V-CONVERSION_METHOD =
ZMHP_INT_CONVERS-CONVERSION_METHOD .
ZMHP_INT_C_V-LAST_CHANGED_AT =
ZMHP_INT_CONVERS-LAST_CHANGED_AT .
ZMHP_INT_C_V-LAST_CHANGED_BY =
ZMHP_INT_CONVERS-LAST_CHANGED_BY .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMHP_INT_C_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMHP_INT_C_V-MOLGA TO
ZMHP_INT_CONVERS-MOLGA .
MOVE ZMHP_INT_C_V-INFTY TO
ZMHP_INT_CONVERS-INFTY .
MOVE ZMHP_INT_C_V-FIELD_SAP TO
ZMHP_INT_CONVERS-FIELD_SAP .
MOVE ZMHP_INT_C_V-MANDT TO
ZMHP_INT_CONVERS-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZMHP_INT_CONVERS'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZMHP_INT_CONVERS TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZMHP_INT_CONVERS'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZMHP_INT_FO_V...................................*
FORM GET_DATA_ZMHP_INT_FO_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZMHP_INT_FOLDERS WHERE
(VIM_WHERETAB) .
    CLEAR ZMHP_INT_FO_V .
ZMHP_INT_FO_V-MANDT =
ZMHP_INT_FOLDERS-MANDT .
ZMHP_INT_FO_V-OBJECT =
ZMHP_INT_FOLDERS-OBJECT .
ZMHP_INT_FO_V-OBJECT_SEQNR =
ZMHP_INT_FOLDERS-OBJECT_SEQNR .
ZMHP_INT_FO_V-MOLGA =
ZMHP_INT_FOLDERS-MOLGA .
ZMHP_INT_FO_V-INFTY =
ZMHP_INT_FOLDERS-INFTY .
ZMHP_INT_FO_V-SEQNR =
ZMHP_INT_FOLDERS-SEQNR .
ZMHP_INT_FO_V-FOLDER =
ZMHP_INT_FOLDERS-FOLDER .
ZMHP_INT_FO_V-PREV_FOLDER =
ZMHP_INT_FOLDERS-PREV_FOLDER .
ZMHP_INT_FO_V-TIME_SLICE =
ZMHP_INT_FOLDERS-TIME_SLICE .
ZMHP_INT_FO_V-LAST_CHANGED_AT =
ZMHP_INT_FOLDERS-LAST_CHANGED_AT .
ZMHP_INT_FO_V-LAST_CHANGED_BY =
ZMHP_INT_FOLDERS-LAST_CHANGED_BY .
<VIM_TOTAL_STRUC> = ZMHP_INT_FO_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMHP_INT_FO_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMHP_INT_FO_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMHP_INT_FO_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_FOLDERS WHERE
  OBJECT = ZMHP_INT_FO_V-OBJECT AND
  OBJECT_SEQNR = ZMHP_INT_FO_V-OBJECT_SEQNR AND
  MOLGA = ZMHP_INT_FO_V-MOLGA AND
  INFTY = ZMHP_INT_FO_V-INFTY AND
  SEQNR = ZMHP_INT_FO_V-SEQNR AND
  FOLDER = ZMHP_INT_FO_V-FOLDER .
    IF SY-SUBRC = 0.
    DELETE ZMHP_INT_FOLDERS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_FOLDERS WHERE
  OBJECT = ZMHP_INT_FO_V-OBJECT AND
  OBJECT_SEQNR = ZMHP_INT_FO_V-OBJECT_SEQNR AND
  MOLGA = ZMHP_INT_FO_V-MOLGA AND
  INFTY = ZMHP_INT_FO_V-INFTY AND
  SEQNR = ZMHP_INT_FO_V-SEQNR AND
  FOLDER = ZMHP_INT_FO_V-FOLDER .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZMHP_INT_FOLDERS.
    ENDIF.
ZMHP_INT_FOLDERS-MANDT =
ZMHP_INT_FO_V-MANDT .
ZMHP_INT_FOLDERS-OBJECT =
ZMHP_INT_FO_V-OBJECT .
ZMHP_INT_FOLDERS-OBJECT_SEQNR =
ZMHP_INT_FO_V-OBJECT_SEQNR .
ZMHP_INT_FOLDERS-MOLGA =
ZMHP_INT_FO_V-MOLGA .
ZMHP_INT_FOLDERS-INFTY =
ZMHP_INT_FO_V-INFTY .
ZMHP_INT_FOLDERS-SEQNR =
ZMHP_INT_FO_V-SEQNR .
ZMHP_INT_FOLDERS-FOLDER =
ZMHP_INT_FO_V-FOLDER .
ZMHP_INT_FOLDERS-PREV_FOLDER =
ZMHP_INT_FO_V-PREV_FOLDER .
ZMHP_INT_FOLDERS-TIME_SLICE =
ZMHP_INT_FO_V-TIME_SLICE .
ZMHP_INT_FOLDERS-LAST_CHANGED_AT =
ZMHP_INT_FO_V-LAST_CHANGED_AT .
ZMHP_INT_FOLDERS-LAST_CHANGED_BY =
ZMHP_INT_FO_V-LAST_CHANGED_BY .
    IF SY-SUBRC = 0.
    UPDATE ZMHP_INT_FOLDERS ##WARN_OK.
    ELSE.
    INSERT ZMHP_INT_FOLDERS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMHP_INT_FO_V-UPD_FLAG,
STATUS_ZMHP_INT_FO_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMHP_INT_FO_V.
  SELECT SINGLE * FROM ZMHP_INT_FOLDERS WHERE
OBJECT = ZMHP_INT_FO_V-OBJECT AND
OBJECT_SEQNR = ZMHP_INT_FO_V-OBJECT_SEQNR AND
MOLGA = ZMHP_INT_FO_V-MOLGA AND
INFTY = ZMHP_INT_FO_V-INFTY AND
SEQNR = ZMHP_INT_FO_V-SEQNR AND
FOLDER = ZMHP_INT_FO_V-FOLDER .
ZMHP_INT_FO_V-MANDT =
ZMHP_INT_FOLDERS-MANDT .
ZMHP_INT_FO_V-OBJECT =
ZMHP_INT_FOLDERS-OBJECT .
ZMHP_INT_FO_V-OBJECT_SEQNR =
ZMHP_INT_FOLDERS-OBJECT_SEQNR .
ZMHP_INT_FO_V-MOLGA =
ZMHP_INT_FOLDERS-MOLGA .
ZMHP_INT_FO_V-INFTY =
ZMHP_INT_FOLDERS-INFTY .
ZMHP_INT_FO_V-SEQNR =
ZMHP_INT_FOLDERS-SEQNR .
ZMHP_INT_FO_V-FOLDER =
ZMHP_INT_FOLDERS-FOLDER .
ZMHP_INT_FO_V-PREV_FOLDER =
ZMHP_INT_FOLDERS-PREV_FOLDER .
ZMHP_INT_FO_V-TIME_SLICE =
ZMHP_INT_FOLDERS-TIME_SLICE .
ZMHP_INT_FO_V-LAST_CHANGED_AT =
ZMHP_INT_FOLDERS-LAST_CHANGED_AT .
ZMHP_INT_FO_V-LAST_CHANGED_BY =
ZMHP_INT_FOLDERS-LAST_CHANGED_BY .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMHP_INT_FO_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMHP_INT_FO_V-OBJECT TO
ZMHP_INT_FOLDERS-OBJECT .
MOVE ZMHP_INT_FO_V-OBJECT_SEQNR TO
ZMHP_INT_FOLDERS-OBJECT_SEQNR .
MOVE ZMHP_INT_FO_V-MOLGA TO
ZMHP_INT_FOLDERS-MOLGA .
MOVE ZMHP_INT_FO_V-INFTY TO
ZMHP_INT_FOLDERS-INFTY .
MOVE ZMHP_INT_FO_V-SEQNR TO
ZMHP_INT_FOLDERS-SEQNR .
MOVE ZMHP_INT_FO_V-FOLDER TO
ZMHP_INT_FOLDERS-FOLDER .
MOVE ZMHP_INT_FO_V-MANDT TO
ZMHP_INT_FOLDERS-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZMHP_INT_FOLDERS'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZMHP_INT_FOLDERS TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZMHP_INT_FOLDERS'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZMHP_INT_FU_V...................................*
FORM GET_DATA_ZMHP_INT_FU_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZMHP_INT_FOUP WHERE
(VIM_WHERETAB) .
    CLEAR ZMHP_INT_FU_V .
ZMHP_INT_FU_V-MANDT =
ZMHP_INT_FOUP-MANDT .
ZMHP_INT_FU_V-MOLGA =
ZMHP_INT_FOUP-MOLGA .
ZMHP_INT_FU_V-MASSN =
ZMHP_INT_FOUP-MASSN .
ZMHP_INT_FU_V-MASSG =
ZMHP_INT_FOUP-MASSG .
ZMHP_INT_FU_V-FOLLOW_UP =
ZMHP_INT_FOUP-FOLLOW_UP .
<VIM_TOTAL_STRUC> = ZMHP_INT_FU_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMHP_INT_FU_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMHP_INT_FU_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMHP_INT_FU_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_FOUP WHERE
  MOLGA = ZMHP_INT_FU_V-MOLGA AND
  MASSG = ZMHP_INT_FU_V-MASSG AND
  MASSN = ZMHP_INT_FU_V-MASSN .
    IF SY-SUBRC = 0.
    DELETE ZMHP_INT_FOUP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_FOUP WHERE
  MOLGA = ZMHP_INT_FU_V-MOLGA AND
  MASSG = ZMHP_INT_FU_V-MASSG AND
  MASSN = ZMHP_INT_FU_V-MASSN .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZMHP_INT_FOUP.
    ENDIF.
ZMHP_INT_FOUP-MANDT =
ZMHP_INT_FU_V-MANDT .
ZMHP_INT_FOUP-MOLGA =
ZMHP_INT_FU_V-MOLGA .
ZMHP_INT_FOUP-MASSN =
ZMHP_INT_FU_V-MASSN .
ZMHP_INT_FOUP-MASSG =
ZMHP_INT_FU_V-MASSG .
ZMHP_INT_FOUP-FOLLOW_UP =
ZMHP_INT_FU_V-FOLLOW_UP .
    IF SY-SUBRC = 0.
    UPDATE ZMHP_INT_FOUP ##WARN_OK.
    ELSE.
    INSERT ZMHP_INT_FOUP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMHP_INT_FU_V-UPD_FLAG,
STATUS_ZMHP_INT_FU_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMHP_INT_FU_V.
  SELECT SINGLE * FROM ZMHP_INT_FOUP WHERE
MOLGA = ZMHP_INT_FU_V-MOLGA AND
MASSG = ZMHP_INT_FU_V-MASSG AND
MASSN = ZMHP_INT_FU_V-MASSN .
ZMHP_INT_FU_V-MANDT =
ZMHP_INT_FOUP-MANDT .
ZMHP_INT_FU_V-MOLGA =
ZMHP_INT_FOUP-MOLGA .
ZMHP_INT_FU_V-MASSN =
ZMHP_INT_FOUP-MASSN .
ZMHP_INT_FU_V-MASSG =
ZMHP_INT_FOUP-MASSG .
ZMHP_INT_FU_V-FOLLOW_UP =
ZMHP_INT_FOUP-FOLLOW_UP .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMHP_INT_FU_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMHP_INT_FU_V-MOLGA TO
ZMHP_INT_FOUP-MOLGA .
MOVE ZMHP_INT_FU_V-MASSG TO
ZMHP_INT_FOUP-MASSG .
MOVE ZMHP_INT_FU_V-MASSN TO
ZMHP_INT_FOUP-MASSN .
MOVE ZMHP_INT_FU_V-MANDT TO
ZMHP_INT_FOUP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZMHP_INT_FOUP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZMHP_INT_FOUP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZMHP_INT_FOUP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZMHP_INT_F_V....................................*
FORM GET_DATA_ZMHP_INT_F_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZMHP_INT_FIELDS WHERE
(VIM_WHERETAB) .
    CLEAR ZMHP_INT_F_V .
ZMHP_INT_F_V-MANDT =
ZMHP_INT_FIELDS-MANDT .
ZMHP_INT_F_V-OBJECT =
ZMHP_INT_FIELDS-OBJECT .
ZMHP_INT_F_V-OBJECT_SEQNR =
ZMHP_INT_FIELDS-OBJECT_SEQNR .
ZMHP_INT_F_V-MOLGA =
ZMHP_INT_FIELDS-MOLGA .
ZMHP_INT_F_V-INFTY =
ZMHP_INT_FIELDS-INFTY .
ZMHP_INT_F_V-SEQNR =
ZMHP_INT_FIELDS-SEQNR .
ZMHP_INT_F_V-FOLDER =
ZMHP_INT_FIELDS-FOLDER .
ZMHP_INT_F_V-FIELD =
ZMHP_INT_FIELDS-FIELD .
ZMHP_INT_F_V-ELEMENT =
ZMHP_INT_FIELDS-ELEMENT .
ZMHP_INT_F_V-IMPORT =
ZMHP_INT_FIELDS-IMPORT .
ZMHP_INT_F_V-EXPORT =
ZMHP_INT_FIELDS-EXPORT .
ZMHP_INT_F_V-CHANGEABLE =
ZMHP_INT_FIELDS-CHANGEABLE .
ZMHP_INT_F_V-LAST_CHANGED_AT =
ZMHP_INT_FIELDS-LAST_CHANGED_AT .
ZMHP_INT_F_V-LAST_CHANGED_BY =
ZMHP_INT_FIELDS-LAST_CHANGED_BY .
<VIM_TOTAL_STRUC> = ZMHP_INT_F_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMHP_INT_F_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMHP_INT_F_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMHP_INT_F_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_FIELDS WHERE
  OBJECT = ZMHP_INT_F_V-OBJECT AND
  OBJECT_SEQNR = ZMHP_INT_F_V-OBJECT_SEQNR AND
  MOLGA = ZMHP_INT_F_V-MOLGA AND
  INFTY = ZMHP_INT_F_V-INFTY AND
  SEQNR = ZMHP_INT_F_V-SEQNR AND
  FOLDER = ZMHP_INT_F_V-FOLDER AND
  FIELD = ZMHP_INT_F_V-FIELD .
    IF SY-SUBRC = 0.
    DELETE ZMHP_INT_FIELDS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_FIELDS WHERE
  OBJECT = ZMHP_INT_F_V-OBJECT AND
  OBJECT_SEQNR = ZMHP_INT_F_V-OBJECT_SEQNR AND
  MOLGA = ZMHP_INT_F_V-MOLGA AND
  INFTY = ZMHP_INT_F_V-INFTY AND
  SEQNR = ZMHP_INT_F_V-SEQNR AND
  FOLDER = ZMHP_INT_F_V-FOLDER AND
  FIELD = ZMHP_INT_F_V-FIELD .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZMHP_INT_FIELDS.
    ENDIF.
ZMHP_INT_FIELDS-MANDT =
ZMHP_INT_F_V-MANDT .
ZMHP_INT_FIELDS-OBJECT =
ZMHP_INT_F_V-OBJECT .
ZMHP_INT_FIELDS-OBJECT_SEQNR =
ZMHP_INT_F_V-OBJECT_SEQNR .
ZMHP_INT_FIELDS-MOLGA =
ZMHP_INT_F_V-MOLGA .
ZMHP_INT_FIELDS-INFTY =
ZMHP_INT_F_V-INFTY .
ZMHP_INT_FIELDS-SEQNR =
ZMHP_INT_F_V-SEQNR .
ZMHP_INT_FIELDS-FOLDER =
ZMHP_INT_F_V-FOLDER .
ZMHP_INT_FIELDS-FIELD =
ZMHP_INT_F_V-FIELD .
ZMHP_INT_FIELDS-ELEMENT =
ZMHP_INT_F_V-ELEMENT .
ZMHP_INT_FIELDS-IMPORT =
ZMHP_INT_F_V-IMPORT .
ZMHP_INT_FIELDS-EXPORT =
ZMHP_INT_F_V-EXPORT .
ZMHP_INT_FIELDS-CHANGEABLE =
ZMHP_INT_F_V-CHANGEABLE .
ZMHP_INT_FIELDS-LAST_CHANGED_AT =
ZMHP_INT_F_V-LAST_CHANGED_AT .
ZMHP_INT_FIELDS-LAST_CHANGED_BY =
ZMHP_INT_F_V-LAST_CHANGED_BY .
    IF SY-SUBRC = 0.
    UPDATE ZMHP_INT_FIELDS ##WARN_OK.
    ELSE.
    INSERT ZMHP_INT_FIELDS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMHP_INT_F_V-UPD_FLAG,
STATUS_ZMHP_INT_F_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMHP_INT_F_V.
  SELECT SINGLE * FROM ZMHP_INT_FIELDS WHERE
OBJECT = ZMHP_INT_F_V-OBJECT AND
OBJECT_SEQNR = ZMHP_INT_F_V-OBJECT_SEQNR AND
MOLGA = ZMHP_INT_F_V-MOLGA AND
INFTY = ZMHP_INT_F_V-INFTY AND
SEQNR = ZMHP_INT_F_V-SEQNR AND
FOLDER = ZMHP_INT_F_V-FOLDER AND
FIELD = ZMHP_INT_F_V-FIELD .
ZMHP_INT_F_V-MANDT =
ZMHP_INT_FIELDS-MANDT .
ZMHP_INT_F_V-OBJECT =
ZMHP_INT_FIELDS-OBJECT .
ZMHP_INT_F_V-OBJECT_SEQNR =
ZMHP_INT_FIELDS-OBJECT_SEQNR .
ZMHP_INT_F_V-MOLGA =
ZMHP_INT_FIELDS-MOLGA .
ZMHP_INT_F_V-INFTY =
ZMHP_INT_FIELDS-INFTY .
ZMHP_INT_F_V-SEQNR =
ZMHP_INT_FIELDS-SEQNR .
ZMHP_INT_F_V-FOLDER =
ZMHP_INT_FIELDS-FOLDER .
ZMHP_INT_F_V-FIELD =
ZMHP_INT_FIELDS-FIELD .
ZMHP_INT_F_V-ELEMENT =
ZMHP_INT_FIELDS-ELEMENT .
ZMHP_INT_F_V-IMPORT =
ZMHP_INT_FIELDS-IMPORT .
ZMHP_INT_F_V-EXPORT =
ZMHP_INT_FIELDS-EXPORT .
ZMHP_INT_F_V-CHANGEABLE =
ZMHP_INT_FIELDS-CHANGEABLE .
ZMHP_INT_F_V-LAST_CHANGED_AT =
ZMHP_INT_FIELDS-LAST_CHANGED_AT .
ZMHP_INT_F_V-LAST_CHANGED_BY =
ZMHP_INT_FIELDS-LAST_CHANGED_BY .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMHP_INT_F_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMHP_INT_F_V-OBJECT TO
ZMHP_INT_FIELDS-OBJECT .
MOVE ZMHP_INT_F_V-OBJECT_SEQNR TO
ZMHP_INT_FIELDS-OBJECT_SEQNR .
MOVE ZMHP_INT_F_V-MOLGA TO
ZMHP_INT_FIELDS-MOLGA .
MOVE ZMHP_INT_F_V-INFTY TO
ZMHP_INT_FIELDS-INFTY .
MOVE ZMHP_INT_F_V-SEQNR TO
ZMHP_INT_FIELDS-SEQNR .
MOVE ZMHP_INT_F_V-FOLDER TO
ZMHP_INT_FIELDS-FOLDER .
MOVE ZMHP_INT_F_V-FIELD TO
ZMHP_INT_FIELDS-FIELD .
MOVE ZMHP_INT_F_V-MANDT TO
ZMHP_INT_FIELDS-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZMHP_INT_FIELDS'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZMHP_INT_FIELDS TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZMHP_INT_FIELDS'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZMHP_INT_G_V....................................*
FORM GET_DATA_ZMHP_INT_G_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZMHP_INT_GENERAL WHERE
(VIM_WHERETAB) .
    CLEAR ZMHP_INT_G_V .
ZMHP_INT_G_V-MANDT =
ZMHP_INT_GENERAL-MANDT .
ZMHP_INT_G_V-FIELD =
ZMHP_INT_GENERAL-FIELD .
ZMHP_INT_G_V-PATH =
ZMHP_INT_GENERAL-PATH .
ZMHP_INT_G_V-LAST_CHANGED_AT =
ZMHP_INT_GENERAL-LAST_CHANGED_AT .
ZMHP_INT_G_V-LAST_CHANGED_BY =
ZMHP_INT_GENERAL-LAST_CHANGED_BY .
<VIM_TOTAL_STRUC> = ZMHP_INT_G_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMHP_INT_G_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMHP_INT_G_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMHP_INT_G_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_GENERAL WHERE
  FIELD = ZMHP_INT_G_V-FIELD .
    IF SY-SUBRC = 0.
    DELETE ZMHP_INT_GENERAL .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_GENERAL WHERE
  FIELD = ZMHP_INT_G_V-FIELD .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZMHP_INT_GENERAL.
    ENDIF.
ZMHP_INT_GENERAL-MANDT =
ZMHP_INT_G_V-MANDT .
ZMHP_INT_GENERAL-FIELD =
ZMHP_INT_G_V-FIELD .
ZMHP_INT_GENERAL-PATH =
ZMHP_INT_G_V-PATH .
ZMHP_INT_GENERAL-LAST_CHANGED_AT =
ZMHP_INT_G_V-LAST_CHANGED_AT .
ZMHP_INT_GENERAL-LAST_CHANGED_BY =
ZMHP_INT_G_V-LAST_CHANGED_BY .
    IF SY-SUBRC = 0.
    UPDATE ZMHP_INT_GENERAL ##WARN_OK.
    ELSE.
    INSERT ZMHP_INT_GENERAL .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMHP_INT_G_V-UPD_FLAG,
STATUS_ZMHP_INT_G_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMHP_INT_G_V.
  SELECT SINGLE * FROM ZMHP_INT_GENERAL WHERE
FIELD = ZMHP_INT_G_V-FIELD .
ZMHP_INT_G_V-MANDT =
ZMHP_INT_GENERAL-MANDT .
ZMHP_INT_G_V-FIELD =
ZMHP_INT_GENERAL-FIELD .
ZMHP_INT_G_V-PATH =
ZMHP_INT_GENERAL-PATH .
ZMHP_INT_G_V-LAST_CHANGED_AT =
ZMHP_INT_GENERAL-LAST_CHANGED_AT .
ZMHP_INT_G_V-LAST_CHANGED_BY =
ZMHP_INT_GENERAL-LAST_CHANGED_BY .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMHP_INT_G_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMHP_INT_G_V-FIELD TO
ZMHP_INT_GENERAL-FIELD .
MOVE ZMHP_INT_G_V-MANDT TO
ZMHP_INT_GENERAL-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZMHP_INT_GENERAL'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZMHP_INT_GENERAL TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZMHP_INT_GENERAL'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZMHP_INT_IG_V...................................*
FORM GET_DATA_ZMHP_INT_IG_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZMHP_INT_INF_GEN WHERE
(VIM_WHERETAB) .
    CLEAR ZMHP_INT_IG_V .
ZMHP_INT_IG_V-MANDT =
ZMHP_INT_INF_GEN-MANDT .
ZMHP_INT_IG_V-MOLGA =
ZMHP_INT_INF_GEN-MOLGA .
ZMHP_INT_IG_V-INFTY =
ZMHP_INT_INF_GEN-INFTY .
ZMHP_INT_IG_V-EARLIEST_CHANGE =
ZMHP_INT_INF_GEN-EARLIEST_CHANGE .
ZMHP_INT_IG_V-LAST_CHANGED_AT =
ZMHP_INT_INF_GEN-LAST_CHANGED_AT .
ZMHP_INT_IG_V-LAST_CHANGED_BY =
ZMHP_INT_INF_GEN-LAST_CHANGED_BY .
<VIM_TOTAL_STRUC> = ZMHP_INT_IG_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMHP_INT_IG_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMHP_INT_IG_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMHP_INT_IG_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_INF_GEN WHERE
  MOLGA = ZMHP_INT_IG_V-MOLGA AND
  INFTY = ZMHP_INT_IG_V-INFTY .
    IF SY-SUBRC = 0.
    DELETE ZMHP_INT_INF_GEN .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_INF_GEN WHERE
  MOLGA = ZMHP_INT_IG_V-MOLGA AND
  INFTY = ZMHP_INT_IG_V-INFTY .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZMHP_INT_INF_GEN.
    ENDIF.
ZMHP_INT_INF_GEN-MANDT =
ZMHP_INT_IG_V-MANDT .
ZMHP_INT_INF_GEN-MOLGA =
ZMHP_INT_IG_V-MOLGA .
ZMHP_INT_INF_GEN-INFTY =
ZMHP_INT_IG_V-INFTY .
ZMHP_INT_INF_GEN-EARLIEST_CHANGE =
ZMHP_INT_IG_V-EARLIEST_CHANGE .
ZMHP_INT_INF_GEN-LAST_CHANGED_AT =
ZMHP_INT_IG_V-LAST_CHANGED_AT .
ZMHP_INT_INF_GEN-LAST_CHANGED_BY =
ZMHP_INT_IG_V-LAST_CHANGED_BY .
    IF SY-SUBRC = 0.
    UPDATE ZMHP_INT_INF_GEN ##WARN_OK.
    ELSE.
    INSERT ZMHP_INT_INF_GEN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMHP_INT_IG_V-UPD_FLAG,
STATUS_ZMHP_INT_IG_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMHP_INT_IG_V.
  SELECT SINGLE * FROM ZMHP_INT_INF_GEN WHERE
MOLGA = ZMHP_INT_IG_V-MOLGA AND
INFTY = ZMHP_INT_IG_V-INFTY .
ZMHP_INT_IG_V-MANDT =
ZMHP_INT_INF_GEN-MANDT .
ZMHP_INT_IG_V-MOLGA =
ZMHP_INT_INF_GEN-MOLGA .
ZMHP_INT_IG_V-INFTY =
ZMHP_INT_INF_GEN-INFTY .
ZMHP_INT_IG_V-EARLIEST_CHANGE =
ZMHP_INT_INF_GEN-EARLIEST_CHANGE .
ZMHP_INT_IG_V-LAST_CHANGED_AT =
ZMHP_INT_INF_GEN-LAST_CHANGED_AT .
ZMHP_INT_IG_V-LAST_CHANGED_BY =
ZMHP_INT_INF_GEN-LAST_CHANGED_BY .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMHP_INT_IG_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMHP_INT_IG_V-MOLGA TO
ZMHP_INT_INF_GEN-MOLGA .
MOVE ZMHP_INT_IG_V-INFTY TO
ZMHP_INT_INF_GEN-INFTY .
MOVE ZMHP_INT_IG_V-MANDT TO
ZMHP_INT_INF_GEN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZMHP_INT_INF_GEN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZMHP_INT_INF_GEN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZMHP_INT_INF_GEN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZMHP_INT_I_V....................................*
FORM GET_DATA_ZMHP_INT_I_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZMHP_INT_INFOTYP WHERE
(VIM_WHERETAB) .
    CLEAR ZMHP_INT_I_V .
ZMHP_INT_I_V-MANDT =
ZMHP_INT_INFOTYP-MANDT .
ZMHP_INT_I_V-OBJECT =
ZMHP_INT_INFOTYP-OBJECT .
ZMHP_INT_I_V-MOLGA =
ZMHP_INT_INFOTYP-MOLGA .
ZMHP_INT_I_V-INFTY =
ZMHP_INT_INFOTYP-INFTY .
ZMHP_INT_I_V-SEQNR =
ZMHP_INT_INFOTYP-SEQNR .
ZMHP_INT_I_V-OBJECT_SEQNR =
ZMHP_INT_INFOTYP-OBJECT_SEQNR .
ZMHP_INT_I_V-LAST_CHANGED_AT =
ZMHP_INT_INFOTYP-LAST_CHANGED_AT .
ZMHP_INT_I_V-LAST_CHANGED_BY =
ZMHP_INT_INFOTYP-LAST_CHANGED_BY .
ZMHP_INT_I_V-MULTIPLE =
ZMHP_INT_INFOTYP-MULTIPLE .
<VIM_TOTAL_STRUC> = ZMHP_INT_I_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMHP_INT_I_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMHP_INT_I_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMHP_INT_I_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_INFOTYP WHERE
  OBJECT = ZMHP_INT_I_V-OBJECT AND
  MOLGA = ZMHP_INT_I_V-MOLGA AND
  INFTY = ZMHP_INT_I_V-INFTY AND
  SEQNR = ZMHP_INT_I_V-SEQNR AND
  OBJECT_SEQNR = ZMHP_INT_I_V-OBJECT_SEQNR .
    IF SY-SUBRC = 0.
    DELETE ZMHP_INT_INFOTYP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_INFOTYP WHERE
  OBJECT = ZMHP_INT_I_V-OBJECT AND
  MOLGA = ZMHP_INT_I_V-MOLGA AND
  INFTY = ZMHP_INT_I_V-INFTY AND
  SEQNR = ZMHP_INT_I_V-SEQNR AND
  OBJECT_SEQNR = ZMHP_INT_I_V-OBJECT_SEQNR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZMHP_INT_INFOTYP.
    ENDIF.
ZMHP_INT_INFOTYP-MANDT =
ZMHP_INT_I_V-MANDT .
ZMHP_INT_INFOTYP-OBJECT =
ZMHP_INT_I_V-OBJECT .
ZMHP_INT_INFOTYP-MOLGA =
ZMHP_INT_I_V-MOLGA .
ZMHP_INT_INFOTYP-INFTY =
ZMHP_INT_I_V-INFTY .
ZMHP_INT_INFOTYP-SEQNR =
ZMHP_INT_I_V-SEQNR .
ZMHP_INT_INFOTYP-OBJECT_SEQNR =
ZMHP_INT_I_V-OBJECT_SEQNR .
ZMHP_INT_INFOTYP-LAST_CHANGED_AT =
ZMHP_INT_I_V-LAST_CHANGED_AT .
ZMHP_INT_INFOTYP-LAST_CHANGED_BY =
ZMHP_INT_I_V-LAST_CHANGED_BY .
ZMHP_INT_INFOTYP-MULTIPLE =
ZMHP_INT_I_V-MULTIPLE .
    IF SY-SUBRC = 0.
    UPDATE ZMHP_INT_INFOTYP ##WARN_OK.
    ELSE.
    INSERT ZMHP_INT_INFOTYP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMHP_INT_I_V-UPD_FLAG,
STATUS_ZMHP_INT_I_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMHP_INT_I_V.
  SELECT SINGLE * FROM ZMHP_INT_INFOTYP WHERE
OBJECT = ZMHP_INT_I_V-OBJECT AND
MOLGA = ZMHP_INT_I_V-MOLGA AND
INFTY = ZMHP_INT_I_V-INFTY AND
SEQNR = ZMHP_INT_I_V-SEQNR AND
OBJECT_SEQNR = ZMHP_INT_I_V-OBJECT_SEQNR .
ZMHP_INT_I_V-MANDT =
ZMHP_INT_INFOTYP-MANDT .
ZMHP_INT_I_V-OBJECT =
ZMHP_INT_INFOTYP-OBJECT .
ZMHP_INT_I_V-MOLGA =
ZMHP_INT_INFOTYP-MOLGA .
ZMHP_INT_I_V-INFTY =
ZMHP_INT_INFOTYP-INFTY .
ZMHP_INT_I_V-SEQNR =
ZMHP_INT_INFOTYP-SEQNR .
ZMHP_INT_I_V-OBJECT_SEQNR =
ZMHP_INT_INFOTYP-OBJECT_SEQNR .
ZMHP_INT_I_V-LAST_CHANGED_AT =
ZMHP_INT_INFOTYP-LAST_CHANGED_AT .
ZMHP_INT_I_V-LAST_CHANGED_BY =
ZMHP_INT_INFOTYP-LAST_CHANGED_BY .
ZMHP_INT_I_V-MULTIPLE =
ZMHP_INT_INFOTYP-MULTIPLE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMHP_INT_I_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMHP_INT_I_V-OBJECT TO
ZMHP_INT_INFOTYP-OBJECT .
MOVE ZMHP_INT_I_V-MOLGA TO
ZMHP_INT_INFOTYP-MOLGA .
MOVE ZMHP_INT_I_V-INFTY TO
ZMHP_INT_INFOTYP-INFTY .
MOVE ZMHP_INT_I_V-SEQNR TO
ZMHP_INT_INFOTYP-SEQNR .
MOVE ZMHP_INT_I_V-OBJECT_SEQNR TO
ZMHP_INT_INFOTYP-OBJECT_SEQNR .
MOVE ZMHP_INT_I_V-MANDT TO
ZMHP_INT_INFOTYP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZMHP_INT_INFOTYP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZMHP_INT_INFOTYP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZMHP_INT_INFOTYP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZMHP_INT_MF_V...................................*
FORM GET_DATA_ZMHP_INT_MF_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZMHP_INT_MAPP_FI WHERE
(VIM_WHERETAB) .
    CLEAR ZMHP_INT_MF_V .
ZMHP_INT_MF_V-MANDT =
ZMHP_INT_MAPP_FI-MANDT .
ZMHP_INT_MF_V-MOLGA =
ZMHP_INT_MAPP_FI-MOLGA .
ZMHP_INT_MF_V-INFTY =
ZMHP_INT_MAPP_FI-INFTY .
ZMHP_INT_MF_V-SEQNR =
ZMHP_INT_MAPP_FI-SEQNR .
ZMHP_INT_MF_V-FIELD_SAP =
ZMHP_INT_MAPP_FI-FIELD_SAP .
ZMHP_INT_MF_V-FIELD_ORACLE =
ZMHP_INT_MAPP_FI-FIELD_ORACLE .
ZMHP_INT_MF_V-IMPORT =
ZMHP_INT_MAPP_FI-IMPORT .
ZMHP_INT_MF_V-EXPORT =
ZMHP_INT_MAPP_FI-EXPORT .
ZMHP_INT_MF_V-IS_COMPLEX =
ZMHP_INT_MAPP_FI-IS_COMPLEX .
ZMHP_INT_MF_V-LAST_CHANGED_AT =
ZMHP_INT_MAPP_FI-LAST_CHANGED_AT .
ZMHP_INT_MF_V-LAST_CHANGED_BY =
ZMHP_INT_MAPP_FI-LAST_CHANGED_BY .
<VIM_TOTAL_STRUC> = ZMHP_INT_MF_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMHP_INT_MF_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMHP_INT_MF_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMHP_INT_MF_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_MAPP_FI WHERE
  MOLGA = ZMHP_INT_MF_V-MOLGA AND
  INFTY = ZMHP_INT_MF_V-INFTY AND
  SEQNR = ZMHP_INT_MF_V-SEQNR AND
  FIELD_SAP = ZMHP_INT_MF_V-FIELD_SAP AND
  FIELD_ORACLE = ZMHP_INT_MF_V-FIELD_ORACLE AND
  IMPORT = ZMHP_INT_MF_V-IMPORT AND
  EXPORT = ZMHP_INT_MF_V-EXPORT .
    IF SY-SUBRC = 0.
    DELETE ZMHP_INT_MAPP_FI .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_MAPP_FI WHERE
  MOLGA = ZMHP_INT_MF_V-MOLGA AND
  INFTY = ZMHP_INT_MF_V-INFTY AND
  SEQNR = ZMHP_INT_MF_V-SEQNR AND
  FIELD_SAP = ZMHP_INT_MF_V-FIELD_SAP AND
  FIELD_ORACLE = ZMHP_INT_MF_V-FIELD_ORACLE AND
  IMPORT = ZMHP_INT_MF_V-IMPORT AND
  EXPORT = ZMHP_INT_MF_V-EXPORT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZMHP_INT_MAPP_FI.
    ENDIF.
ZMHP_INT_MAPP_FI-MANDT =
ZMHP_INT_MF_V-MANDT .
ZMHP_INT_MAPP_FI-MOLGA =
ZMHP_INT_MF_V-MOLGA .
ZMHP_INT_MAPP_FI-INFTY =
ZMHP_INT_MF_V-INFTY .
ZMHP_INT_MAPP_FI-SEQNR =
ZMHP_INT_MF_V-SEQNR .
ZMHP_INT_MAPP_FI-FIELD_SAP =
ZMHP_INT_MF_V-FIELD_SAP .
ZMHP_INT_MAPP_FI-FIELD_ORACLE =
ZMHP_INT_MF_V-FIELD_ORACLE .
ZMHP_INT_MAPP_FI-IMPORT =
ZMHP_INT_MF_V-IMPORT .
ZMHP_INT_MAPP_FI-EXPORT =
ZMHP_INT_MF_V-EXPORT .
ZMHP_INT_MAPP_FI-IS_COMPLEX =
ZMHP_INT_MF_V-IS_COMPLEX .
ZMHP_INT_MAPP_FI-LAST_CHANGED_AT =
ZMHP_INT_MF_V-LAST_CHANGED_AT .
ZMHP_INT_MAPP_FI-LAST_CHANGED_BY =
ZMHP_INT_MF_V-LAST_CHANGED_BY .
    IF SY-SUBRC = 0.
    UPDATE ZMHP_INT_MAPP_FI ##WARN_OK.
    ELSE.
    INSERT ZMHP_INT_MAPP_FI .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMHP_INT_MF_V-UPD_FLAG,
STATUS_ZMHP_INT_MF_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMHP_INT_MF_V.
  SELECT SINGLE * FROM ZMHP_INT_MAPP_FI WHERE
MOLGA = ZMHP_INT_MF_V-MOLGA AND
INFTY = ZMHP_INT_MF_V-INFTY AND
SEQNR = ZMHP_INT_MF_V-SEQNR AND
FIELD_SAP = ZMHP_INT_MF_V-FIELD_SAP AND
FIELD_ORACLE = ZMHP_INT_MF_V-FIELD_ORACLE AND
IMPORT = ZMHP_INT_MF_V-IMPORT AND
EXPORT = ZMHP_INT_MF_V-EXPORT .
ZMHP_INT_MF_V-MANDT =
ZMHP_INT_MAPP_FI-MANDT .
ZMHP_INT_MF_V-MOLGA =
ZMHP_INT_MAPP_FI-MOLGA .
ZMHP_INT_MF_V-INFTY =
ZMHP_INT_MAPP_FI-INFTY .
ZMHP_INT_MF_V-SEQNR =
ZMHP_INT_MAPP_FI-SEQNR .
ZMHP_INT_MF_V-FIELD_SAP =
ZMHP_INT_MAPP_FI-FIELD_SAP .
ZMHP_INT_MF_V-FIELD_ORACLE =
ZMHP_INT_MAPP_FI-FIELD_ORACLE .
ZMHP_INT_MF_V-IMPORT =
ZMHP_INT_MAPP_FI-IMPORT .
ZMHP_INT_MF_V-EXPORT =
ZMHP_INT_MAPP_FI-EXPORT .
ZMHP_INT_MF_V-IS_COMPLEX =
ZMHP_INT_MAPP_FI-IS_COMPLEX .
ZMHP_INT_MF_V-LAST_CHANGED_AT =
ZMHP_INT_MAPP_FI-LAST_CHANGED_AT .
ZMHP_INT_MF_V-LAST_CHANGED_BY =
ZMHP_INT_MAPP_FI-LAST_CHANGED_BY .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMHP_INT_MF_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMHP_INT_MF_V-MOLGA TO
ZMHP_INT_MAPP_FI-MOLGA .
MOVE ZMHP_INT_MF_V-INFTY TO
ZMHP_INT_MAPP_FI-INFTY .
MOVE ZMHP_INT_MF_V-SEQNR TO
ZMHP_INT_MAPP_FI-SEQNR .
MOVE ZMHP_INT_MF_V-FIELD_SAP TO
ZMHP_INT_MAPP_FI-FIELD_SAP .
MOVE ZMHP_INT_MF_V-FIELD_ORACLE TO
ZMHP_INT_MAPP_FI-FIELD_ORACLE .
MOVE ZMHP_INT_MF_V-IMPORT TO
ZMHP_INT_MAPP_FI-IMPORT .
MOVE ZMHP_INT_MF_V-EXPORT TO
ZMHP_INT_MAPP_FI-EXPORT .
MOVE ZMHP_INT_MF_V-MANDT TO
ZMHP_INT_MAPP_FI-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZMHP_INT_MAPP_FI'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZMHP_INT_MAPP_FI TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZMHP_INT_MAPP_FI'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZMHP_INT_M_V....................................*
FORM GET_DATA_ZMHP_INT_M_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZMHP_INT_MAPPING WHERE
(VIM_WHERETAB) .
    CLEAR ZMHP_INT_M_V .
ZMHP_INT_M_V-MADNT =
ZMHP_INT_MAPPING-MANDT .
ZMHP_INT_M_V-MOLGA =
ZMHP_INT_MAPPING-MOLGA .
ZMHP_INT_M_V-INFTY =
ZMHP_INT_MAPPING-INFTY .
ZMHP_INT_M_V-FIELD_SAP =
ZMHP_INT_MAPPING-FIELD_SAP .
ZMHP_INT_M_V-FIELD_ORACLE =
ZMHP_INT_MAPPING-FIELD_ORACLE .
ZMHP_INT_M_V-VALUE_SAP =
ZMHP_INT_MAPPING-VALUE_SAP .
ZMHP_INT_M_V-VALUE_ORACLE =
ZMHP_INT_MAPPING-VALUE_ORACLE .
ZMHP_INT_M_V-IMPORT =
ZMHP_INT_MAPPING-IMPORT .
ZMHP_INT_M_V-SEQNR =
ZMHP_INT_MAPPING-SEQNR .
ZMHP_INT_M_V-EXPORT =
ZMHP_INT_MAPPING-EXPORT .
ZMHP_INT_M_V-LAST_CHANGED_AT =
ZMHP_INT_MAPPING-LAST_CHANGED_AT .
ZMHP_INT_M_V-LAST_CHANGED_BY =
ZMHP_INT_MAPPING-LAST_CHANGED_BY .
<VIM_TOTAL_STRUC> = ZMHP_INT_M_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMHP_INT_M_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMHP_INT_M_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMHP_INT_M_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_MAPPING WHERE
  MOLGA = ZMHP_INT_M_V-MOLGA AND
  INFTY = ZMHP_INT_M_V-INFTY AND
  SEQNR = ZMHP_INT_M_V-SEQNR AND
  FIELD_SAP = ZMHP_INT_M_V-FIELD_SAP AND
  FIELD_ORACLE = ZMHP_INT_M_V-FIELD_ORACLE AND
  IMPORT = ZMHP_INT_M_V-IMPORT AND
  EXPORT = ZMHP_INT_M_V-EXPORT AND
  VALUE_SAP = ZMHP_INT_M_V-VALUE_SAP AND
  VALUE_ORACLE = ZMHP_INT_M_V-VALUE_ORACLE .
    IF SY-SUBRC = 0.
    DELETE ZMHP_INT_MAPPING .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_MAPPING WHERE
  MOLGA = ZMHP_INT_M_V-MOLGA AND
  INFTY = ZMHP_INT_M_V-INFTY AND
  SEQNR = ZMHP_INT_M_V-SEQNR AND
  FIELD_SAP = ZMHP_INT_M_V-FIELD_SAP AND
  FIELD_ORACLE = ZMHP_INT_M_V-FIELD_ORACLE AND
  IMPORT = ZMHP_INT_M_V-IMPORT AND
  EXPORT = ZMHP_INT_M_V-EXPORT AND
  VALUE_SAP = ZMHP_INT_M_V-VALUE_SAP AND
  VALUE_ORACLE = ZMHP_INT_M_V-VALUE_ORACLE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZMHP_INT_MAPPING.
    ENDIF.
ZMHP_INT_MAPPING-MANDT =
ZMHP_INT_M_V-MADNT .
ZMHP_INT_MAPPING-MOLGA =
ZMHP_INT_M_V-MOLGA .
ZMHP_INT_MAPPING-INFTY =
ZMHP_INT_M_V-INFTY .
ZMHP_INT_MAPPING-FIELD_SAP =
ZMHP_INT_M_V-FIELD_SAP .
ZMHP_INT_MAPPING-FIELD_ORACLE =
ZMHP_INT_M_V-FIELD_ORACLE .
ZMHP_INT_MAPPING-VALUE_SAP =
ZMHP_INT_M_V-VALUE_SAP .
ZMHP_INT_MAPPING-VALUE_ORACLE =
ZMHP_INT_M_V-VALUE_ORACLE .
ZMHP_INT_MAPPING-IMPORT =
ZMHP_INT_M_V-IMPORT .
ZMHP_INT_MAPPING-SEQNR =
ZMHP_INT_M_V-SEQNR .
ZMHP_INT_MAPPING-EXPORT =
ZMHP_INT_M_V-EXPORT .
ZMHP_INT_MAPPING-LAST_CHANGED_AT =
ZMHP_INT_M_V-LAST_CHANGED_AT .
ZMHP_INT_MAPPING-LAST_CHANGED_BY =
ZMHP_INT_M_V-LAST_CHANGED_BY .
    IF SY-SUBRC = 0.
    UPDATE ZMHP_INT_MAPPING ##WARN_OK.
    ELSE.
    INSERT ZMHP_INT_MAPPING .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMHP_INT_M_V-UPD_FLAG,
STATUS_ZMHP_INT_M_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMHP_INT_M_V.
  SELECT SINGLE * FROM ZMHP_INT_MAPPING WHERE
MOLGA = ZMHP_INT_M_V-MOLGA AND
INFTY = ZMHP_INT_M_V-INFTY AND
SEQNR = ZMHP_INT_M_V-SEQNR AND
FIELD_SAP = ZMHP_INT_M_V-FIELD_SAP AND
FIELD_ORACLE = ZMHP_INT_M_V-FIELD_ORACLE AND
IMPORT = ZMHP_INT_M_V-IMPORT AND
EXPORT = ZMHP_INT_M_V-EXPORT AND
VALUE_SAP = ZMHP_INT_M_V-VALUE_SAP AND
VALUE_ORACLE = ZMHP_INT_M_V-VALUE_ORACLE .
ZMHP_INT_M_V-MADNT =
ZMHP_INT_MAPPING-MANDT .
ZMHP_INT_M_V-MOLGA =
ZMHP_INT_MAPPING-MOLGA .
ZMHP_INT_M_V-INFTY =
ZMHP_INT_MAPPING-INFTY .
ZMHP_INT_M_V-FIELD_SAP =
ZMHP_INT_MAPPING-FIELD_SAP .
ZMHP_INT_M_V-FIELD_ORACLE =
ZMHP_INT_MAPPING-FIELD_ORACLE .
ZMHP_INT_M_V-VALUE_SAP =
ZMHP_INT_MAPPING-VALUE_SAP .
ZMHP_INT_M_V-VALUE_ORACLE =
ZMHP_INT_MAPPING-VALUE_ORACLE .
ZMHP_INT_M_V-IMPORT =
ZMHP_INT_MAPPING-IMPORT .
ZMHP_INT_M_V-SEQNR =
ZMHP_INT_MAPPING-SEQNR .
ZMHP_INT_M_V-EXPORT =
ZMHP_INT_MAPPING-EXPORT .
ZMHP_INT_M_V-LAST_CHANGED_AT =
ZMHP_INT_MAPPING-LAST_CHANGED_AT .
ZMHP_INT_M_V-LAST_CHANGED_BY =
ZMHP_INT_MAPPING-LAST_CHANGED_BY .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMHP_INT_M_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMHP_INT_M_V-MOLGA TO
ZMHP_INT_MAPPING-MOLGA .
MOVE ZMHP_INT_M_V-INFTY TO
ZMHP_INT_MAPPING-INFTY .
MOVE ZMHP_INT_M_V-SEQNR TO
ZMHP_INT_MAPPING-SEQNR .
MOVE ZMHP_INT_M_V-FIELD_SAP TO
ZMHP_INT_MAPPING-FIELD_SAP .
MOVE ZMHP_INT_M_V-FIELD_ORACLE TO
ZMHP_INT_MAPPING-FIELD_ORACLE .
MOVE ZMHP_INT_M_V-IMPORT TO
ZMHP_INT_MAPPING-IMPORT .
MOVE ZMHP_INT_M_V-EXPORT TO
ZMHP_INT_MAPPING-EXPORT .
MOVE ZMHP_INT_M_V-VALUE_SAP TO
ZMHP_INT_MAPPING-VALUE_SAP .
MOVE ZMHP_INT_M_V-VALUE_ORACLE TO
ZMHP_INT_MAPPING-VALUE_ORACLE .
MOVE ZMHP_INT_M_V-MADNT TO
ZMHP_INT_MAPPING-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZMHP_INT_MAPPING'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZMHP_INT_MAPPING TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZMHP_INT_MAPPING'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZMHP_INT_N_V....................................*
FORM GET_DATA_ZMHP_INT_N_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZMHP_INT_NOTES WHERE
(VIM_WHERETAB) .
    CLEAR ZMHP_INT_N_V .
ZMHP_INT_N_V-MANDT =
ZMHP_INT_NOTES-MANDT .
ZMHP_INT_N_V-MOLGA =
ZMHP_INT_NOTES-MOLGA .
ZMHP_INT_N_V-MSGID =
ZMHP_INT_NOTES-MSGID .
ZMHP_INT_N_V-MSGNO =
ZMHP_INT_NOTES-MSGNO .
ZMHP_INT_N_V-MSGTY =
ZMHP_INT_NOTES-MSGTY .
ZMHP_INT_N_V-MSGTEXT =
ZMHP_INT_NOTES-MSGTEXT .
<VIM_TOTAL_STRUC> = ZMHP_INT_N_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMHP_INT_N_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMHP_INT_N_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMHP_INT_N_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_NOTES WHERE
  MOLGA = ZMHP_INT_N_V-MOLGA AND
  MSGID = ZMHP_INT_N_V-MSGID AND
  MSGNO = ZMHP_INT_N_V-MSGNO AND
  MSGTY = ZMHP_INT_N_V-MSGTY .
    IF SY-SUBRC = 0.
    DELETE ZMHP_INT_NOTES .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_NOTES WHERE
  MOLGA = ZMHP_INT_N_V-MOLGA AND
  MSGID = ZMHP_INT_N_V-MSGID AND
  MSGNO = ZMHP_INT_N_V-MSGNO AND
  MSGTY = ZMHP_INT_N_V-MSGTY .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZMHP_INT_NOTES.
    ENDIF.
ZMHP_INT_NOTES-MANDT =
ZMHP_INT_N_V-MANDT .
ZMHP_INT_NOTES-MOLGA =
ZMHP_INT_N_V-MOLGA .
ZMHP_INT_NOTES-MSGID =
ZMHP_INT_N_V-MSGID .
ZMHP_INT_NOTES-MSGNO =
ZMHP_INT_N_V-MSGNO .
ZMHP_INT_NOTES-MSGTY =
ZMHP_INT_N_V-MSGTY .
ZMHP_INT_NOTES-MSGTEXT =
ZMHP_INT_N_V-MSGTEXT .
    IF SY-SUBRC = 0.
    UPDATE ZMHP_INT_NOTES ##WARN_OK.
    ELSE.
    INSERT ZMHP_INT_NOTES .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMHP_INT_N_V-UPD_FLAG,
STATUS_ZMHP_INT_N_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMHP_INT_N_V.
  SELECT SINGLE * FROM ZMHP_INT_NOTES WHERE
MOLGA = ZMHP_INT_N_V-MOLGA AND
MSGID = ZMHP_INT_N_V-MSGID AND
MSGNO = ZMHP_INT_N_V-MSGNO AND
MSGTY = ZMHP_INT_N_V-MSGTY .
ZMHP_INT_N_V-MANDT =
ZMHP_INT_NOTES-MANDT .
ZMHP_INT_N_V-MOLGA =
ZMHP_INT_NOTES-MOLGA .
ZMHP_INT_N_V-MSGID =
ZMHP_INT_NOTES-MSGID .
ZMHP_INT_N_V-MSGNO =
ZMHP_INT_NOTES-MSGNO .
ZMHP_INT_N_V-MSGTY =
ZMHP_INT_NOTES-MSGTY .
ZMHP_INT_N_V-MSGTEXT =
ZMHP_INT_NOTES-MSGTEXT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMHP_INT_N_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMHP_INT_N_V-MOLGA TO
ZMHP_INT_NOTES-MOLGA .
MOVE ZMHP_INT_N_V-MSGID TO
ZMHP_INT_NOTES-MSGID .
MOVE ZMHP_INT_N_V-MSGNO TO
ZMHP_INT_NOTES-MSGNO .
MOVE ZMHP_INT_N_V-MSGTY TO
ZMHP_INT_NOTES-MSGTY .
MOVE ZMHP_INT_N_V-MANDT TO
ZMHP_INT_NOTES-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZMHP_INT_NOTES'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZMHP_INT_NOTES TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZMHP_INT_NOTES'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZMHP_INT_O_V....................................*
FORM GET_DATA_ZMHP_INT_O_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZMHP_INT_OBJECTS WHERE
(VIM_WHERETAB) .
    CLEAR ZMHP_INT_O_V .
ZMHP_INT_O_V-MANDT =
ZMHP_INT_OBJECTS-MANDT .
ZMHP_INT_O_V-MOLGA =
ZMHP_INT_OBJECTS-MOLGA .
ZMHP_INT_O_V-OBJECT =
ZMHP_INT_OBJECTS-OBJECT .
ZMHP_INT_O_V-OBJECT_SEQNR =
ZMHP_INT_OBJECTS-OBJECT_SEQNR .
ZMHP_INT_O_V-SCENARIO =
ZMHP_INT_OBJECTS-SCENARIO .
ZMHP_INT_O_V-FOLDER =
ZMHP_INT_OBJECTS-FOLDER .
ZMHP_INT_O_V-ID_SAP =
ZMHP_INT_OBJECTS-ID_SAP .
ZMHP_INT_O_V-ID_ORACLE =
ZMHP_INT_OBJECTS-ID_ORACLE .
ZMHP_INT_O_V-LAST_CHANGED_AT =
ZMHP_INT_OBJECTS-LAST_CHANGED_AT .
ZMHP_INT_O_V-LAST_CHANGED_BY =
ZMHP_INT_OBJECTS-LAST_CHANGED_BY .
<VIM_TOTAL_STRUC> = ZMHP_INT_O_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMHP_INT_O_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMHP_INT_O_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMHP_INT_O_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_OBJECTS WHERE
  MOLGA = ZMHP_INT_O_V-MOLGA AND
  OBJECT = ZMHP_INT_O_V-OBJECT AND
  OBJECT_SEQNR = ZMHP_INT_O_V-OBJECT_SEQNR .
    IF SY-SUBRC = 0.
    DELETE ZMHP_INT_OBJECTS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_OBJECTS WHERE
  MOLGA = ZMHP_INT_O_V-MOLGA AND
  OBJECT = ZMHP_INT_O_V-OBJECT AND
  OBJECT_SEQNR = ZMHP_INT_O_V-OBJECT_SEQNR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZMHP_INT_OBJECTS.
    ENDIF.
ZMHP_INT_OBJECTS-MANDT =
ZMHP_INT_O_V-MANDT .
ZMHP_INT_OBJECTS-MOLGA =
ZMHP_INT_O_V-MOLGA .
ZMHP_INT_OBJECTS-OBJECT =
ZMHP_INT_O_V-OBJECT .
ZMHP_INT_OBJECTS-OBJECT_SEQNR =
ZMHP_INT_O_V-OBJECT_SEQNR .
ZMHP_INT_OBJECTS-SCENARIO =
ZMHP_INT_O_V-SCENARIO .
ZMHP_INT_OBJECTS-FOLDER =
ZMHP_INT_O_V-FOLDER .
ZMHP_INT_OBJECTS-ID_SAP =
ZMHP_INT_O_V-ID_SAP .
ZMHP_INT_OBJECTS-ID_ORACLE =
ZMHP_INT_O_V-ID_ORACLE .
ZMHP_INT_OBJECTS-LAST_CHANGED_AT =
ZMHP_INT_O_V-LAST_CHANGED_AT .
ZMHP_INT_OBJECTS-LAST_CHANGED_BY =
ZMHP_INT_O_V-LAST_CHANGED_BY .
    IF SY-SUBRC = 0.
    UPDATE ZMHP_INT_OBJECTS ##WARN_OK.
    ELSE.
    INSERT ZMHP_INT_OBJECTS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMHP_INT_O_V-UPD_FLAG,
STATUS_ZMHP_INT_O_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMHP_INT_O_V.
  SELECT SINGLE * FROM ZMHP_INT_OBJECTS WHERE
MOLGA = ZMHP_INT_O_V-MOLGA AND
OBJECT = ZMHP_INT_O_V-OBJECT AND
OBJECT_SEQNR = ZMHP_INT_O_V-OBJECT_SEQNR .
ZMHP_INT_O_V-MANDT =
ZMHP_INT_OBJECTS-MANDT .
ZMHP_INT_O_V-MOLGA =
ZMHP_INT_OBJECTS-MOLGA .
ZMHP_INT_O_V-OBJECT =
ZMHP_INT_OBJECTS-OBJECT .
ZMHP_INT_O_V-OBJECT_SEQNR =
ZMHP_INT_OBJECTS-OBJECT_SEQNR .
ZMHP_INT_O_V-SCENARIO =
ZMHP_INT_OBJECTS-SCENARIO .
ZMHP_INT_O_V-FOLDER =
ZMHP_INT_OBJECTS-FOLDER .
ZMHP_INT_O_V-ID_SAP =
ZMHP_INT_OBJECTS-ID_SAP .
ZMHP_INT_O_V-ID_ORACLE =
ZMHP_INT_OBJECTS-ID_ORACLE .
ZMHP_INT_O_V-LAST_CHANGED_AT =
ZMHP_INT_OBJECTS-LAST_CHANGED_AT .
ZMHP_INT_O_V-LAST_CHANGED_BY =
ZMHP_INT_OBJECTS-LAST_CHANGED_BY .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMHP_INT_O_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMHP_INT_O_V-MOLGA TO
ZMHP_INT_OBJECTS-MOLGA .
MOVE ZMHP_INT_O_V-OBJECT TO
ZMHP_INT_OBJECTS-OBJECT .
MOVE ZMHP_INT_O_V-OBJECT_SEQNR TO
ZMHP_INT_OBJECTS-OBJECT_SEQNR .
MOVE ZMHP_INT_O_V-MANDT TO
ZMHP_INT_OBJECTS-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZMHP_INT_OBJECTS'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZMHP_INT_OBJECTS TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZMHP_INT_OBJECTS'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZMHP_INT_S......................................*
FORM GET_DATA_ZMHP_INT_S.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZMHP_INT_SUPERUS WHERE
(VIM_WHERETAB) .
    CLEAR ZMHP_INT_S .
ZMHP_INT_S-MANDT =
ZMHP_INT_SUPERUS-MANDT .
ZMHP_INT_S-SBGRP_CODE =
ZMHP_INT_SUPERUS-SBGRP_CODE .
ZMHP_INT_S-SB_CODE =
ZMHP_INT_SUPERUS-SB_CODE .
ZMHP_INT_S-BUKRS =
ZMHP_INT_SUPERUS-BUKRS .
ZMHP_INT_S-UNAME =
ZMHP_INT_SUPERUS-UNAME .
ZMHP_INT_S-BEGDA =
ZMHP_INT_SUPERUS-BEGDA .
ZMHP_INT_S-ENDDA =
ZMHP_INT_SUPERUS-ENDDA .
<VIM_TOTAL_STRUC> = ZMHP_INT_S.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMHP_INT_S .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMHP_INT_S.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMHP_INT_S-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_SUPERUS WHERE
  SBGRP_CODE = ZMHP_INT_S-SBGRP_CODE AND
  SB_CODE = ZMHP_INT_S-SB_CODE AND
  BUKRS = ZMHP_INT_S-BUKRS AND
  UNAME = ZMHP_INT_S-UNAME .
    IF SY-SUBRC = 0.
    DELETE ZMHP_INT_SUPERUS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_SUPERUS WHERE
  SBGRP_CODE = ZMHP_INT_S-SBGRP_CODE AND
  SB_CODE = ZMHP_INT_S-SB_CODE AND
  BUKRS = ZMHP_INT_S-BUKRS AND
  UNAME = ZMHP_INT_S-UNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZMHP_INT_SUPERUS.
    ENDIF.
ZMHP_INT_SUPERUS-MANDT =
ZMHP_INT_S-MANDT .
ZMHP_INT_SUPERUS-SBGRP_CODE =
ZMHP_INT_S-SBGRP_CODE .
ZMHP_INT_SUPERUS-SB_CODE =
ZMHP_INT_S-SB_CODE .
ZMHP_INT_SUPERUS-BUKRS =
ZMHP_INT_S-BUKRS .
ZMHP_INT_SUPERUS-UNAME =
ZMHP_INT_S-UNAME .
ZMHP_INT_SUPERUS-BEGDA =
ZMHP_INT_S-BEGDA .
ZMHP_INT_SUPERUS-ENDDA =
ZMHP_INT_S-ENDDA .
    IF SY-SUBRC = 0.
    UPDATE ZMHP_INT_SUPERUS ##WARN_OK.
    ELSE.
    INSERT ZMHP_INT_SUPERUS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMHP_INT_S-UPD_FLAG,
STATUS_ZMHP_INT_S-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZMHP_INT_S.
  SELECT SINGLE * FROM ZMHP_INT_SUPERUS WHERE
SBGRP_CODE = ZMHP_INT_S-SBGRP_CODE AND
SB_CODE = ZMHP_INT_S-SB_CODE AND
BUKRS = ZMHP_INT_S-BUKRS AND
UNAME = ZMHP_INT_S-UNAME .
ZMHP_INT_S-MANDT =
ZMHP_INT_SUPERUS-MANDT .
ZMHP_INT_S-SBGRP_CODE =
ZMHP_INT_SUPERUS-SBGRP_CODE .
ZMHP_INT_S-SB_CODE =
ZMHP_INT_SUPERUS-SB_CODE .
ZMHP_INT_S-BUKRS =
ZMHP_INT_SUPERUS-BUKRS .
ZMHP_INT_S-UNAME =
ZMHP_INT_SUPERUS-UNAME .
ZMHP_INT_S-BEGDA =
ZMHP_INT_SUPERUS-BEGDA .
ZMHP_INT_S-ENDDA =
ZMHP_INT_SUPERUS-ENDDA .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMHP_INT_S USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMHP_INT_S-SBGRP_CODE TO
ZMHP_INT_SUPERUS-SBGRP_CODE .
MOVE ZMHP_INT_S-SB_CODE TO
ZMHP_INT_SUPERUS-SB_CODE .
MOVE ZMHP_INT_S-BUKRS TO
ZMHP_INT_SUPERUS-BUKRS .
MOVE ZMHP_INT_S-UNAME TO
ZMHP_INT_SUPERUS-UNAME .
MOVE ZMHP_INT_S-MANDT TO
ZMHP_INT_SUPERUS-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZMHP_INT_SUPERUS'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZMHP_INT_SUPERUS TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZMHP_INT_SUPERUS'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZMHP_INT_V_V....................................*
FORM GET_DATA_ZMHP_INT_V_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZMHP_INT_VALUES WHERE
(VIM_WHERETAB) .
    CLEAR ZMHP_INT_V_V .
ZMHP_INT_V_V-MANDT =
ZMHP_INT_VALUES-MANDT .
ZMHP_INT_V_V-OBJECT =
ZMHP_INT_VALUES-OBJECT .
ZMHP_INT_V_V-MOLGA =
ZMHP_INT_VALUES-MOLGA .
ZMHP_INT_V_V-INFTY =
ZMHP_INT_VALUES-INFTY .
ZMHP_INT_V_V-FIELD =
ZMHP_INT_VALUES-FIELD .
ZMHP_INT_V_V-VALUE =
ZMHP_INT_VALUES-VALUE .
ZMHP_INT_V_V-LAST_CHANGED_AT =
ZMHP_INT_VALUES-LAST_CHANGED_AT .
ZMHP_INT_V_V-LAST_CHANGED_BY =
ZMHP_INT_VALUES-LAST_CHANGED_BY .
<VIM_TOTAL_STRUC> = ZMHP_INT_V_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMHP_INT_V_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMHP_INT_V_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMHP_INT_V_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_VALUES WHERE
  OBJECT = ZMHP_INT_V_V-OBJECT AND
  MOLGA = ZMHP_INT_V_V-MOLGA AND
  INFTY = ZMHP_INT_V_V-INFTY AND
  FIELD = ZMHP_INT_V_V-FIELD .
    IF SY-SUBRC = 0.
    DELETE ZMHP_INT_VALUES .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZMHP_INT_VALUES WHERE
  OBJECT = ZMHP_INT_V_V-OBJECT AND
  MOLGA = ZMHP_INT_V_V-MOLGA AND
  INFTY = ZMHP_INT_V_V-INFTY AND
  FIELD = ZMHP_INT_V_V-FIELD .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZMHP_INT_VALUES.
    ENDIF.
ZMHP_INT_VALUES-MANDT =
ZMHP_INT_V_V-MANDT .
ZMHP_INT_VALUES-OBJECT =
ZMHP_INT_V_V-OBJECT .
ZMHP_INT_VALUES-MOLGA =
ZMHP_INT_V_V-MOLGA .
ZMHP_INT_VALUES-INFTY =
ZMHP_INT_V_V-INFTY .
ZMHP_INT_VALUES-FIELD =
ZMHP_INT_V_V-FIELD .
ZMHP_INT_VALUES-VALUE =
ZMHP_INT_V_V-VALUE .
ZMHP_INT_VALUES-LAST_CHANGED_AT =
ZMHP_INT_V_V-LAST_CHANGED_AT .
ZMHP_INT_VALUES-LAST_CHANGED_BY =
ZMHP_INT_V_V-LAST_CHANGED_BY .
    IF SY-SUBRC = 0.
    UPDATE ZMHP_INT_VALUES ##WARN_OK.
    ELSE.
    INSERT ZMHP_INT_VALUES .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMHP_INT_V_V-UPD_FLAG,
STATUS_ZMHP_INT_V_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMHP_INT_V_V.
  SELECT SINGLE * FROM ZMHP_INT_VALUES WHERE
OBJECT = ZMHP_INT_V_V-OBJECT AND
MOLGA = ZMHP_INT_V_V-MOLGA AND
INFTY = ZMHP_INT_V_V-INFTY AND
FIELD = ZMHP_INT_V_V-FIELD .
ZMHP_INT_V_V-MANDT =
ZMHP_INT_VALUES-MANDT .
ZMHP_INT_V_V-OBJECT =
ZMHP_INT_VALUES-OBJECT .
ZMHP_INT_V_V-MOLGA =
ZMHP_INT_VALUES-MOLGA .
ZMHP_INT_V_V-INFTY =
ZMHP_INT_VALUES-INFTY .
ZMHP_INT_V_V-FIELD =
ZMHP_INT_VALUES-FIELD .
ZMHP_INT_V_V-VALUE =
ZMHP_INT_VALUES-VALUE .
ZMHP_INT_V_V-LAST_CHANGED_AT =
ZMHP_INT_VALUES-LAST_CHANGED_AT .
ZMHP_INT_V_V-LAST_CHANGED_BY =
ZMHP_INT_VALUES-LAST_CHANGED_BY .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMHP_INT_V_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMHP_INT_V_V-OBJECT TO
ZMHP_INT_VALUES-OBJECT .
MOVE ZMHP_INT_V_V-MOLGA TO
ZMHP_INT_VALUES-MOLGA .
MOVE ZMHP_INT_V_V-INFTY TO
ZMHP_INT_VALUES-INFTY .
MOVE ZMHP_INT_V_V-FIELD TO
ZMHP_INT_VALUES-FIELD .
MOVE ZMHP_INT_V_V-MANDT TO
ZMHP_INT_VALUES-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZMHP_INT_VALUES'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZMHP_INT_VALUES TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZMHP_INT_VALUES'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
