*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: ZMHP_INT_C_V....................................*
TABLES: ZMHP_INT_C_V, *ZMHP_INT_C_V. "view work areas
CONTROLS: TCTRL_ZMHP_INT_C_V
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_ZMHP_INT_C_V. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZMHP_INT_C_V.
* Table for entries selected to show on screen
DATA: BEGIN OF ZMHP_INT_C_V_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_C_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_C_V_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZMHP_INT_C_V_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_C_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_C_V_TOTAL.

*...processing: ZMHP_INT_FO_V...................................*
TABLES: ZMHP_INT_FO_V, *ZMHP_INT_FO_V. "view work areas
CONTROLS: TCTRL_ZMHP_INT_FO_V
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_ZMHP_INT_FO_V. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZMHP_INT_FO_V.
* Table for entries selected to show on screen
DATA: BEGIN OF ZMHP_INT_FO_V_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_FO_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_FO_V_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZMHP_INT_FO_V_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_FO_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_FO_V_TOTAL.

*...processing: ZMHP_INT_FU_V...................................*
TABLES: ZMHP_INT_FU_V, *ZMHP_INT_FU_V. "view work areas
CONTROLS: TCTRL_ZMHP_INT_FU_V
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_ZMHP_INT_FU_V. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZMHP_INT_FU_V.
* Table for entries selected to show on screen
DATA: BEGIN OF ZMHP_INT_FU_V_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_FU_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_FU_V_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZMHP_INT_FU_V_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_FU_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_FU_V_TOTAL.

*...processing: ZMHP_INT_F_V....................................*
TABLES: ZMHP_INT_F_V, *ZMHP_INT_F_V. "view work areas
CONTROLS: TCTRL_ZMHP_INT_F_V
TYPE TABLEVIEW USING SCREEN '0004'.
DATA: BEGIN OF STATUS_ZMHP_INT_F_V. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZMHP_INT_F_V.
* Table for entries selected to show on screen
DATA: BEGIN OF ZMHP_INT_F_V_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_F_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_F_V_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZMHP_INT_F_V_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_F_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_F_V_TOTAL.

*...processing: ZMHP_INT_G_V....................................*
TABLES: ZMHP_INT_G_V, *ZMHP_INT_G_V. "view work areas
CONTROLS: TCTRL_ZMHP_INT_G_V
TYPE TABLEVIEW USING SCREEN '0006'.
DATA: BEGIN OF STATUS_ZMHP_INT_G_V. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZMHP_INT_G_V.
* Table for entries selected to show on screen
DATA: BEGIN OF ZMHP_INT_G_V_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_G_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_G_V_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZMHP_INT_G_V_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_G_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_G_V_TOTAL.

*...processing: ZMHP_INT_IG_V...................................*
TABLES: ZMHP_INT_IG_V, *ZMHP_INT_IG_V. "view work areas
CONTROLS: TCTRL_ZMHP_INT_IG_V
TYPE TABLEVIEW USING SCREEN '0007'.
DATA: BEGIN OF STATUS_ZMHP_INT_IG_V. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZMHP_INT_IG_V.
* Table for entries selected to show on screen
DATA: BEGIN OF ZMHP_INT_IG_V_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_IG_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_IG_V_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZMHP_INT_IG_V_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_IG_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_IG_V_TOTAL.

*...processing: ZMHP_INT_I_V....................................*
TABLES: ZMHP_INT_I_V, *ZMHP_INT_I_V. "view work areas
CONTROLS: TCTRL_ZMHP_INT_I_V
TYPE TABLEVIEW USING SCREEN '0008'.
DATA: BEGIN OF STATUS_ZMHP_INT_I_V. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZMHP_INT_I_V.
* Table for entries selected to show on screen
DATA: BEGIN OF ZMHP_INT_I_V_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_I_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_I_V_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZMHP_INT_I_V_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_I_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_I_V_TOTAL.

*...processing: ZMHP_INT_MF_V...................................*
TABLES: ZMHP_INT_MF_V, *ZMHP_INT_MF_V. "view work areas
CONTROLS: TCTRL_ZMHP_INT_MF_V
TYPE TABLEVIEW USING SCREEN '0009'.
DATA: BEGIN OF STATUS_ZMHP_INT_MF_V. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZMHP_INT_MF_V.
* Table for entries selected to show on screen
DATA: BEGIN OF ZMHP_INT_MF_V_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_MF_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_MF_V_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZMHP_INT_MF_V_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_MF_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_MF_V_TOTAL.

*...processing: ZMHP_INT_M_V....................................*
TABLES: ZMHP_INT_M_V, *ZMHP_INT_M_V. "view work areas
CONTROLS: TCTRL_ZMHP_INT_M_V
TYPE TABLEVIEW USING SCREEN '0011'.
DATA: BEGIN OF STATUS_ZMHP_INT_M_V. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZMHP_INT_M_V.
* Table for entries selected to show on screen
DATA: BEGIN OF ZMHP_INT_M_V_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_M_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_M_V_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZMHP_INT_M_V_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_M_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_M_V_TOTAL.

*...processing: ZMHP_INT_N_V....................................*
TABLES: ZMHP_INT_N_V, *ZMHP_INT_N_V. "view work areas
CONTROLS: TCTRL_ZMHP_INT_N_V
TYPE TABLEVIEW USING SCREEN '0012'.
DATA: BEGIN OF STATUS_ZMHP_INT_N_V. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZMHP_INT_N_V.
* Table for entries selected to show on screen
DATA: BEGIN OF ZMHP_INT_N_V_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_N_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_N_V_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZMHP_INT_N_V_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_N_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_N_V_TOTAL.

*...processing: ZMHP_INT_O_V....................................*
TABLES: ZMHP_INT_O_V, *ZMHP_INT_O_V. "view work areas
CONTROLS: TCTRL_ZMHP_INT_O_V
TYPE TABLEVIEW USING SCREEN '0013'.
DATA: BEGIN OF STATUS_ZMHP_INT_O_V. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZMHP_INT_O_V.
* Table for entries selected to show on screen
DATA: BEGIN OF ZMHP_INT_O_V_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_O_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_O_V_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZMHP_INT_O_V_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_O_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_O_V_TOTAL.

*...processing: ZMHP_INT_REL_FLD................................*
DATA:  BEGIN OF STATUS_ZMHP_INT_REL_FLD              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZMHP_INT_REL_FLD              .
CONTROLS: TCTRL_ZMHP_INT_REL_FLD
            TYPE TABLEVIEW USING SCREEN '0018'.
*...processing: ZMHP_INT_S......................................*
TABLES: ZMHP_INT_S, *ZMHP_INT_S. "view work areas
CONTROLS: TCTRL_ZMHP_INT_S
TYPE TABLEVIEW USING SCREEN '0015'.
DATA: BEGIN OF STATUS_ZMHP_INT_S. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZMHP_INT_S.
* Table for entries selected to show on screen
DATA: BEGIN OF ZMHP_INT_S_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_S.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_S_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZMHP_INT_S_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_S.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_S_TOTAL.

*...processing: ZMHP_INT_SUPERUS................................*
DATA:  BEGIN OF STATUS_ZMHP_INT_SUPERUS              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZMHP_INT_SUPERUS              .
CONTROLS: TCTRL_ZMHP_INT_SUPERUS
            TYPE TABLEVIEW USING SCREEN '0017'.
*...processing: ZMHP_INT_V_V....................................*
TABLES: ZMHP_INT_V_V, *ZMHP_INT_V_V. "view work areas
CONTROLS: TCTRL_ZMHP_INT_V_V
TYPE TABLEVIEW USING SCREEN '0016'.
DATA: BEGIN OF STATUS_ZMHP_INT_V_V. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZMHP_INT_V_V.
* Table for entries selected to show on screen
DATA: BEGIN OF ZMHP_INT_V_V_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_V_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_V_V_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZMHP_INT_V_V_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZMHP_INT_V_V.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMHP_INT_V_V_TOTAL.

*.........table declarations:.................................*
TABLES: *ZMHP_INT_REL_FLD              .
TABLES: *ZMHP_INT_SUPERUS              .
TABLES: ZMHP_INT_CONVERS               .
TABLES: ZMHP_INT_FIELDS                .
TABLES: ZMHP_INT_FOLDERS               .
TABLES: ZMHP_INT_FOUP                  .
TABLES: ZMHP_INT_GENERAL               .
TABLES: ZMHP_INT_INFOTYP               .
TABLES: ZMHP_INT_INF_GEN               .
TABLES: ZMHP_INT_MAPPING               .
TABLES: ZMHP_INT_MAPP_FI               .
TABLES: ZMHP_INT_NOTES                 .
TABLES: ZMHP_INT_OBJECTS               .
TABLES: ZMHP_INT_REL_FLD               .
TABLES: ZMHP_INT_SUPERUS               .
TABLES: ZMHP_INT_VALUES                .

* general table data declarations..............
  INCLUDE LSVIMTDT                                .
